# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('collectionId', models.IntegerField(primary_key=True, serialize=False)),
                ('collectionName', models.TextField()),
                ('releaseDate', models.DateField(default=datetime.date.today)),
                ('artworkUrl100', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistId', models.IntegerField(primary_key=True, serialize=False)),
                ('artistName', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistsApp.Artist'),
        ),
    ]
